### ISSUE TITLE
frustrated

### ISSUE THREAD

**Issue by Freaky-cyper** [iseeyoucopy/U-232-Trinity-RC#26]
On the install for Trinity, it is very frustrating,  it comes up that i don't have opcache installed / set-up;

[Ran this command] sudo apt-get install php-opcache

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'php7.4-opcache' instead of 'php-opcache'
php7.4-opcache is already the newest version (7.4.3-4ubuntu2.4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

But as you can see, is it is.
What is the next step for me?
Thank you
P.S. I have made the changes in php.ini, that is called to activate.

**Comment by iseeyoucopy** [comment]
The problem didn't was the opcache module 
it was something to do with permissioncheck.php 
it didn't let you to go to next step because i comment one line in there and i forgot to uncomment

it is fixed now
https://github.com/iseeyoucopy/U-232-Trinity-RC/commit/a59c732a57f85a5ead7335e58872551084eba029

**Comment by Freaky-cyper** [comment]
Thank you. Works now :)
